[package]
name = "fm-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
common = { workspace = true }
nodeinnet-p2p = { workspace = true }
async-trait = "0.1"
uuid = { version = "1.7", features = ["v4", "fast-rng"] }
tokio = { version = "1", features = ["sync"] }
