[package]
name = "gtk-viewer-ui"
version = "0.1.286"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
gtk = { package = "gtk4", version = "0.9", features = ["v4_12"] }
adw = { package = "libadwaita", version = "0.7", features = ["v1_6"] }
nodeinnet-i18n = { workspace = true }
fm-core = { workspace = true }
common = { workspace = true }

[dev-dependencies]
