[package]
name = "common"
version = "0.1.286"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
# installer.rs restarts the app after an update
nodeinnet-utils = { workspace = true }

[dev-dependencies]
serde_json = "1.0"
